# app.py

import os
from pathlib import Path
from typing import List

import streamlit as st
from dotenv import load_dotenv

from utils.extract_text import extract_text_any
from utils.chapters import split_into_chapters
from utils.enrich_text import enrich_for_audiobook
from utils.tts import text_to_speech_mp3

# Load environment variables (GEMINI_API_KEY)
load_dotenv()

# Ensure audio output directory exists
Path("outputs/audio").mkdir(parents=True, exist_ok=True)

st.set_page_config(
    page_title="AI Audiobook Generator (Gemini)",
    page_icon="🎧",
    layout="centered",
)


def main():
    st.title("🎧 AI Audiobook Generator (Gemini + gTTS)")
    st.write(
        "Upload **PDF**, **DOCX**, or **TXT** files. "
        "For each chapter, you can listen to audio of the **actual content** "
        "and also a **rephrased audiobook-style version** generated by Google Gemini."
    )

    # File uploader (supports multiple files)
    uploaded_files = st.file_uploader(
        "Upload documents",
        type=["pdf", "docx", "txt"],
        accept_multiple_files=True,
        help="You can upload multiple files; each will be processed separately.",
    )

    # TTS language selection
    tts_lang = st.selectbox(
        "Select TTS language",
        options=["en", "hi"],
        index=0,
        help="Language for spoken audio. Example: en = English, hi = Hindi.",
    )

    # Accent / tld selection
    accent = st.selectbox(
        "Select voice accent (approx.)",
        options=["com", "co.in", "co.uk", "com.au"],
        index=1,
        help="com = US, co.in = Indian, co.uk = British, com.au = Australian (approx).",
    )

    # Slow / normal speech
    slow_voice = st.checkbox("Use slower speech", value=False)

    # Single button with state variable
    generate_clicked = st.button("Generate Audiobooks")

    if generate_clicked:
        if uploaded_files:
            process_files(
                uploaded_files=uploaded_files,
                tts_lang=tts_lang,
                accent=accent,
                slow_voice=slow_voice,
            )
        else:
            st.warning("Please upload at least one file.")


def process_files(uploaded_files: List, tts_lang: str, accent: str, slow_voice: bool):
    """
    Process all uploaded files: extract text, split into chapters,
    generate original + rephrased audio per chapter.
    """
    for file in uploaded_files:
        file_name = file.name
        base_name = Path(file_name).stem

        st.header(f"📄 {file_name}")

        try:
            # 1. Extract raw text
            raw_text = extract_text_any(file_name, file)
            if not raw_text.strip():
                st.error("No text could be extracted from this file.")
                continue

            st.subheader("Extracted Text (Preview)")
            st.text_area(
                "Raw text preview",
                raw_text[:2000],
                height=200,
                disabled=True,
            )

            # 2. Split into chapters
            chapters = split_into_chapters(raw_text)
            if not chapters:
                st.error("No chapters/content found after splitting.")
                continue

            st.success(f"Found {len(chapters)} chapter(s).")

            # 3. Process each chapter
            for ch_idx, ch_text in enumerate(chapters, start=1):
                st.markdown(f"## 🎧 Chapter {ch_idx}")

                # 3a. Show ORIGINAL text
                st.markdown("#### 📌 Actual Content")
                st.text_area(
                    f"Actual Text - Chapter {ch_idx}",
                    ch_text[:2000],
                    height=220,
                    disabled=True,
                )

                # 3b. Rephrase using Gemini
                with st.spinner(f"Rephrasing Chapter {ch_idx} with Gemini..."):
                    enriched_text = enrich_for_audiobook(ch_text)

                st.markdown("#### ✨ Rephrased Content")
                st.text_area(
                    f"Rephrased Text - Chapter {ch_idx}",
                    enriched_text[:2000],
                    height=220,
                    disabled=True,
                )

                ch_base_name = f"{base_name}_chapter_{ch_idx}"

                # 3c. Generate BOTH audios: original + rephrased
                with st.spinner(
                    f"Generating audio for Chapter {ch_idx} (original & rephrased)..."
                ):
                    # Original audio (actual content)
                    orig_path, orig_bytes = text_to_speech_mp3(
                        ch_text,
                        output_dir="outputs/audio",
                        base_name=f"{ch_base_name}_original",
                        lang=tts_lang,
                        slow=slow_voice,
                        tld=accent,
                    )

                    # Rephrased audio (Gemini version)
                    reph_path, reph_bytes = text_to_speech_mp3(
                        enriched_text,
                        output_dir="outputs/audio",
                        base_name=f"{ch_base_name}_rephrased",
                        lang=tts_lang,
                        slow=slow_voice,
                        tld=accent,
                    )

                # 3d. Player + download for ORIGINAL audio
                st.markdown("##### 🔊 Original Audio")
                st.audio(orig_bytes, format="audio/mp3")
                st.download_button(
                    label=f"⬇️ Download Original Audio – Chapter {ch_idx}",
                    data=orig_bytes,
                    file_name=os.path.basename(orig_path),
                    mime="audio/mpeg",
                    key=f"download_original_{ch_base_name}",
                )

                # 3e. Player + download for REPHRASED audio
                st.markdown("##### 🎙 Rephrased Audio")
                st.audio(reph_bytes, format="audio/mp3")
                st.download_button(
                    label=f"⬇️ Download Rephrased Audio – Chapter {ch_idx}",
                    data=reph_bytes,
                    file_name=os.path.basename(reph_path),
                    mime="audio/mpeg",
                    key=f"download_rephrased_{ch_base_name}",
                )

        except Exception as e:
            st.error(f"Error processing {file_name}: {e}")


if __name__ == "__main__":
    main()
